name: GitOps.PullRequestIssueManagement
description: GitHub policy for triaging and managing pull requests and issues.
resource: repository
disabled: false

where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 'If if open issue and label Needs: Author Feedback and Status: No Recent Activity with no update after 3 days, then close the issue.'
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - hasLabel:
          label: 'Status: No Recent Activity'
      - noActivitySince:
          days: 3
      actions:
      - closeIssue

    - description: 'If open issue and label is Needs: Author Feedback is applied with no update after 4 days, then apply label "Status: No Recent Activity'
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - noActivitySince:
          days: 4
      - isNotLabeledWith:
          label: 'Status: No Recent Activity'
      actions:
      - addLabel:
          label: 'Status: No Recent Activity'
      - addReply:
          reply: This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**.

    - description: 'If open issue and label is Resolution: Duplicate with no activity for 1 day, close issue.'
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Resolution: Duplicate'
      - noActivitySince:
          days: 1
      actions:
      - addReply:
          reply: This issue has been marked as duplicate and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
      - closeIssue

    - description: 'If open pr and label includes Needs: Author Feedback and Status: No Recent Activity with no update after 7 days, then close the issue.'
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - hasLabel:
          label: 'Status: No Recent Activity'
      - noActivitySince:
          days: 7
      actions:
      - closeIssue

    - description: 'If open pull request and label includes Needs: Author Feedback and has not been updated in 7 days, then add label and request update.'
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: 'Needs: Author Feedback'
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: 'Status: No Recent Activity'
      actions:
      - addLabel:
          label: 'Status: No Recent Activity'
      - addReply:
          reply: This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.

    eventResponderTasks:
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'Needs: Author Feedback'
      - isOpen
      then:
      - addLabel:
          label: 'Needs: Attention :wave:'
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 'If author comments on issue with label Needs: Author Feedback, then adjust labels'

    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      description: 'If issue is closed and had Status: No Recent Activity, then remove the label.'

    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      description: 'If comment on issue and has label Status: No Recent Activity, then remove the label.'

    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Submitted
      - isReviewState:
          reviewState: Changes_requested
      then:
      - addLabel:
          label: 'Needs: Author Feedback'
      description: 'If pr has review that requests changes, then add label.'

    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          issueAuthor: True
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 'If pr has label Needs: Author Feedback and is closed, then remove label.'

    - if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 'If issue has label Needs: Author Feedback and author comments, then remove label.'

    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 'If pull request has label Needs: Author Feedback and author updates, then remove label.'

    - if:
      - payloadType: Pull_Request
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      description: 'If pull request has label Status: No Recent Activity and is closed, then remove label.'

    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      description: 'If issue has new comment and has label Status: No Recent Activity, then remove label.'

    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      description: 'If pull request has update and has label Status: No Recent Activity, then remove label.'

    - if:
      - payloadType: Issue_Comment
      then:
      - cleanEmailReply
      description: 'If issue has new comment then perform cleanEmailReply action.'

    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: 'Auto-Merge :heavy_check_mark:'
      then:
      - enableAutoMerge:
          mergeMethod: Squash
      description: 'If pr opened and has label auto-merge :heavy_check_mark: added, then disableAutoMerge.'

    - if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: 'Auto-Merge :heavy_check_mark:'
      then:
      - disableAutoMerge
      description: 'If pr opened and has label auto-merge :heavy_check_mark: removed, then disableAutoMerge.'
onFailure:
onSuccess:
