// Azure Resource Graph Query
// Provides a list of Azure App Service Plans where Autoscale/Automatic scaling is not enabled to ensure adequate resources are available to service requests

resources
| where type == "microsoft.web/serverfarms"
| where properties['elasticScaleEnabled'] contains 'false' and properties['maximumElasticWorkerCount'] < 2
| project recommendationId = '6320abf6-f917-1843-b2ae-4779c35985ae', name, id, param1= "Automatic Scaling not enabled"
| order by id
