// Azure Resource Graph Query
// This query will return all Private Endpoints that are not in a Succeeded state
resources
| where type =~ "microsoft.network/privateendpoints"
| where (properties.provisioningState =~ "Succeeded" and (properties.privateLinkServiceConnections[0].properties.provisioningState =~ "Succeeded" or properties.manualPrivateLinkServiceConnections[0].properties.provisioningState =~ "Succeeded")) == false
| project recommendationId = "b89c9acc-0aba-fb44-9ff2-3dbfcf97dce7", name, id, tags, param1 = strcat("provisioningState: ", tostring(properties.provisioningState)), param2 = strcat("provisioningState: ", tostring(properties.privateLinkServiceConnections[0].properties.provisioningState)), param3 = strcat("manualProvisioningState: ", tostring(properties.manualPrivateLinkServiceConnections[0].properties.provisioningState))
