// Azure Resource Graph Query
// The query filters the qualified Container app environments that do not have Zone Redundancy enabled.
// Its important to check regions that support availability zones for Container app environments https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support

resources
| where type == "microsoft.app/managedenvironments"
| extend zoneRedundant = tobool(properties.zoneRedundant)
| project recommendationId = "f4201965-a88d-449d-b3b4-021394719eb2", name, id, tags, param1 = "AvailabilityZones: Single Zone"
| order by id asc
