list(include('recommendation'), min=1)

---
recommendation:
  description: str(max=100)
  aprlGuid: regex('^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
  recommendationTypeId: any(regex('^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'), null())
  recommendationControl: enum('HighAvailability', 'BusinessContinuity', 'DisasterRecovery', 'Scalability', 'MonitoringAndAlerting', 'ServiceUpgradeAndRetirement', 'OtherBestPractices', 'Personalized', 'Governance', 'Security')
  recommendationImpact: enum('Low', 'Medium', 'High')
  recommendationResourceType: any(
    regex('^Microsoft\\.[a-zA-Z0-9.]+/[a-zA-Z0-9]+$'),
    regex('^WellArchitected/[A-Za-z]+$'),
    regex('^Specialized\\.Workload/[A-Za-z]+$'))
  recommendationMetadataState: enum('Active', 'Disabled')
  longDescription: str(max=300)
  potentialBenefits: str(max=60)
  pgVerified: bool()
  automationAvailable: bool()
  tags: null()
  learnMoreLink: list(include('linkItem'), required=False, min=1)

linkItem:
  name: str()
  url: str()
