list(include('recommendation'), min=1)

---
recommendation:
  description: str(max=100)
  aprlGuid: regex('^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
  recommendationTypeId: any(regex('^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'), null())
  recommendationControl: enum('High Availability', 'Business Continuity', 'Disaster Recovery', 'Scalability', 'Monitoring and Alerting', 'Service Upgrade and Retirement', 'Other Best Practices', 'Personalized', 'Governance', 'Security')
  recommendationImpact: enum('Low', 'Medium', 'High')
  recommendationResourceType: regex('^Specialized.Workload/[A-Za-z]+$')
  recommendationMetadataState: enum('Active', 'Disabled')
  longDescription: str()
  potentialBenefits: str(max=60)
  pgVerified: bool()
  publishedToLearn: bool()
  automationAvailable: bool()
  tags: null()
  learnMoreLink: list()
