// Azure Resource Graph Query
// Displays all recovery services vaults that do not have cross region restore enabled
resources
| where type =~ "Microsoft.RecoveryServices/vaults" and
    properties.redundancySettings.crossRegionRestore !~ "Enabled"
| extend
    param1 = strcat("CrossRegionRestore: ", properties.redundancySettings.crossRegionRestore),
    param2 = strcat("StorageReplicationType: ", properties.redundancySettings.standardTierStorageRedundancy)
| project recommendationId = "1549b91f-2ea0-4d4f-ba2a-4596becbe3de", name, id, tags, param1, param2
