// Azure Resource Graph Query
// Check if App Service has minimum instance count of 2

resources
| where type =~ 'microsoft.web/sites'
| where properties.kind has 'app'
| join kind = inner
    (
    appserviceresources
    | where properties.PreWarmedInstanceCount < 2
    | project name
    ) on name
| project recommendationId = "9e6682ac-31bc-4635-9959-ab74b52454e6", name, id, kind, param1 = "PreWarmedInstanceCount is less than 2"