// Azure Resource Graph Query
// Find Database for MySQL instances that do not have geo redundant backup storage enabled
resources
| where type =~ "microsoft.dbformysql/flexibleservers"
| where properties.backup.geoRedundantBackup != "Enabled"
| project recommendationId = "5c96afc3-7d2e-46ff-a4c7-9c32850c441b", name, id, tags, param1 = strcat("geoRedundantBackup:", properties['backup']['geoRedundantBackup'])