// Azure Resource Graph Query
// Find Database for MySQL instances that do not have a custom maintenance window
resources
| where type =~ "microsoft.dbformysql/flexibleservers"
| where properties.maintenanceWindow.customWindow != "Enabled"
| project recommendationId = "82a9a0f2-24ee-496f-9ad2-25f81710942d", name, id, tags, param1 = strcat("customWindow:", properties['maintenanceWindow']['customWindow'])