// Azure Resource Graph Query
// Find Database for PostgreSQL instances that do not have geo redundant backup storage configured
resources
| where type == "microsoft.dbforpostgresql/flexibleservers"
| where properties.backup.geoRedundantBackup != "Enabled"
| project recommendationId = "31f4ac4b-29cb-4588-8de2-d8fe6f13ceb3", name, id, tags, param1 = strcat("geoRedundantBackup:", properties['backup']['geoRedundantBackup'])
