// Azure Resource Graph Query
// Find Database for PostgreSQL instances that do not have a custom maintenance window
resources
| where type == "microsoft.dbforpostgresql/flexibleservers"
| where properties.maintenanceWindow.customWindow != "Enabled"
| project recommendationId = "b2bad57d-7e03-4c0f-9024-597c9eb295bb", name, id, tags, param1 = strcat("customWindow:", properties['maintenanceWindow']['customWindow'])

