name: Sync Issues to Azure DevOps Work Items

permissions:
  contents: read

on:
  issues:
    types: [opened, closed, deleted, reopened, edited, labeled, unlabeled, assigned, unassigned]
  issue_comment:
    types: [created]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync workflow
    if: github.repository == 'Azure/Azure-Proactive-Resiliency-Library-v2'

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: GitHub/ADO Sync
        uses: a11smiles/GitSync@74d80b4ef67578135781e76ee1d4add1b98969b1 # v1.2.3
        env:
          ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
          github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
          ado.autoCreate: 'true'
          config_file: './.github/actions-config/gh-ado-sync-config.json'
        with:
          ado: ${{ secrets.ADO_MAPPINGS_HANDLES }}
