name: Test Hardened PR Workflow

on:
  workflow_dispatch:
    inputs:
      simulate_pr_number:
        description: "PR number to simulate (for logs only)"
        required: false
        default: "123"

permissions:
  contents: read
  pull-requests: read

jobs:
  test-hardened:
    name: Validate Hardened Workflow Logic
    runs-on: ubuntu-latest

    steps:
      # 1) Harden Runner (AUDIT mode for testing – no blocks yet)
      - name: Harden Runner (audit mode)
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
            egress-policy: audit

      # 2) Checkout THIS repository/branch so files are available in the workspace
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          fetch-depth: 1

      # 3) Simulate PR metadata (purely informational)
      - name: Simulate PR Context
        run: |
          echo "Simulating PR #${{ github.event.inputs.simulate_pr_number }}"
          echo "Base branch: main"
          echo "PR branch  : (simulated)"

      # 4) Show what is actually in .github/scripts to debug paths quickly
      - name: List .github/scripts (if present)
        run: |
          echo "Listing .github/scripts..."
          ls -la .github/scripts || echo "::warning::.github/scripts not found in this repo/branch"

      # 5) Integrity Check (guarded): compute hash only if the file exists
      - name: Integrity Check (guarded)
        id: integrity
        shell: bash
        env:
          FILE_PATH: ".github/scripts/validate-kql-comments.ps1"
        run: |
          set -euo pipefail
          echo "Running integrity check..."
          if [[ ! -f "$FILE_PATH" ]]; then
            echo "::warning:: $FILE_PATH not found in this repository/branch. Skipping integrity check."
            echo "found=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          base_hash="$(sha256sum "$FILE_PATH" | cut -d ' ' -f1)"
          echo "Base hash: $base_hash"
          # For this TEST workflow we simply pass when file exists and hash is computed.
          echo "found=true"  >> "$GITHUB_OUTPUT"
          echo "hash=$base_hash" >> "$GITHUB_OUTPUT"

      # 6) Conditional Execution Simulation (purely illustrative)
      - name: Check Approval Condition (simulated)
        run: |
          echo "Simulating reviewDecision = APPROVED"
          echo "PR approved"

      # 7) Mock Azure Login (no secrets)
      - name: Mock Azure Login
        run: |
          echo "Simulating Azure OIDC login"
          echo "Client ID: dummy"
          echo "Tenant ID: dummy"
          echo "Subscription ID: dummy"

      # 8) Simulate KQL Validation
      - name: Run KQL Validation (Dry Run)
        shell: pwsh
        run: |
          Write-Host "Simulating KQL validation"
          Write-Host "No real scripts executed"